### ISSUE TITLE
Avoid use of spaces in folder names?

### ISSUE THREAD

**Issue by andrerom** [ezsystems/requirements#17]

**Comment by DavidLiedle** [comment]
Exploring the proposed change, as an example:

/eZ Platform/Admin UI/Multi-File Upload/
would become
/eZPlatform/AdminUI/Multi-FileUpload/

https://github.com/ezsystems/requirements/tree/master/eZ%20Platform/Admin%20UI/Multi-File%20Upload
would become
https://github.com/ezsystems/requirements/tree/master/eZPlatform/AdminUI/Multi-FileUpload

IMHO, readability would improve in URLs, and decline in folder names.

The change to DX would affect the occasional instances when the tab key does not autocomplete, remedied by usage of the \ escape character or the use of a modern CLI suite such as http://ohmyz.sh/ or the FISH shell: https://fishshell.com/

Open for discussion.

**Comment by bdunogier** [comment]
We have been using underscores & lower case in our specs trees, for what it's worth.

**Comment by DavidLiedle** [comment]
For code-based projects, I always lean that way as well (lowercase_underscored), but the majority of the users/readers of this repo will be using the GitHub GUI app and their Finder / Windows Explorer to view. Matching the modern style in macOS / Windows made sense.

**Comment by bdunogier** [comment]
Then in that case, I would stick to spaces instead of dashes.
